# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Actions on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  mutation_testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4.2.1
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Execute pitest
          run: ./gradlew pitest

  mutation_testing_action:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4.2.1
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Execute PITest
          uses: isamadrid90/gradle-pitest-comment-action@v2.0.0
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
